#
# application.yml — главный конфигурационный файл Spring Boot.

spring:
  profiles:
    active: development
---
spring:
  config:
    activate:
      on-profile: development

  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/bankrest_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog/db.changelog-master.yaml

  auth:
    jwt:
      access: bankrest
      refresh: bankrest

  card-number:
    encryption:
      secret: bankrestcardcard

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    doc-expansion: none
    default-model-expand-depth: 1
    default-model-rendering: example
    default-models-expand-depth: 1
    deep-linking: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    persist-authorization: true
    show-common-extensions: true
    show-extensions: true
    try-it-out-enabled: true
    urls:
      - url: /api-docs
        name: Bank Cards API

  packages-to-scan:
    - com.example.bankcards.controller
    - com.example.bankcards.entity
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  cache:
    disabled: true

server:
  port: 8080

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

